apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  labels:
    app: backend-app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: backend-app
  type: LoadBalancer